services:
  php:
    build: ./docker/
    container_name: blog-php
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
  nginx:
    image: nginx
    container_name: blog-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
  mysql:
    image: mysql:5.7
    container_name: blog-mysql
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      TZ: "Asia/Yerevan"
    ports:
      - "3306:3306"
